# Generated by Django 4.1.5 on 2023-01-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="related",
            field=models.ManyToManyField(blank=True, to="ideas.idea"),
        ),
    ]
